server:
  # Render's dynamic port detection
  port: ${PORT:8082}

spring:
  application:
    name: ride-service
  datasource:
    # Cloud (Railway/Render) and Local fallback
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecoride_ride_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:sourabh@2003}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

razorpay:
  key-id: ${RAZORPAY_KEY_ID:rzp_test_RpjVgDaher9T9K}
  key-secret: ${RAZORPAY_KEY_SECRET:x7KUDJhqTmGP140UlliF9lrC}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

eureka:
  instance:
    # Render environment needs hostname-based discovery
    prefer-ip-address: false
    hostname: ecoride-ride-service.onrender.com
    non-secure-port: ${server.port}
  client:
    service-url:
      # Use the live Cloud Eureka URL
      defaultZone: ${EUREKA_SERVER_URL:https://service-registry-qhsy.onrender.com/eureka/}
    register-with-eureka: true
    fetch-registry: true