server:
  port: ${PORT:8082}

spring:
  application:
    name: ride-service
  datasource:
    # Local pe 'localhost' aur Cloud pe Railway ka URL auto-pick hoga
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecoride_ride_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:sourabh@2003}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

razorpay:
  key-id: ${RAZORPAY_KEY_ID:rzp_test_RpjVgDaher9T9K}
  key-secret: ${RAZORPAY_KEY_SECRET:x7KUDJhqTmGP140UlliF9lrC}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      # Local/Docker registry fallback ke saath
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}